#!/bin/bash
# Overnight content generation for Open Knowledge Graph
# Generates explainers for all topics, then questions (prioritized by hub-ness + stage)
#
# Usage:
#   cd ~/open-knowledge-graph
#   nohup bash tools/overnight/run-content-overnight.sh > tools/overnight/content-nohup.out 2>&1 &
#
# Check progress:
#   python ~/.claude/scripts/overnight.py tools/overnight/explainer-manifest.json --status
#   python ~/.claude/scripts/overnight.py tools/overnight/questions-manifest.json --status

set -e
cd "$(dirname "$0")/../.."

PYTHON="/c/Python314/python"
RUNNER="$HOME/.claude/scripts/overnight.py"

echo "=============================================="
echo "OKG Content Generation — $(date)"
echo "=============================================="

# Phase 1: Explainers
echo ""
echo "PHASE 1: Generating explainers for 12,483 topics..."
echo "Started: $(date)"
$PYTHON "$RUNNER" tools/overnight/explainer-manifest.json
echo "Phase 1 finished: $(date)"

# Commit explainers
echo "Committing explainer progress..."
git add domains/
git commit -m "Add explainer sections (overnight batch)

Generated by overnight orchestrator using Opus 4.6.

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>" || echo "Nothing to commit for explainers"

# Phase 2: Questions
echo ""
echo "PHASE 2: Generating questions (prioritized by hub connectivity + stage)..."
echo "Started: $(date)"
$PYTHON "$RUNNER" tools/overnight/questions-manifest.json
echo "Phase 2 finished: $(date)"

# Commit questions
echo "Committing question progress..."
git add domains/
git commit -m "Add question sections (overnight batch)

Generated by overnight orchestrator using Opus 4.6.
Priority: hub topics first, younger developmental stages weighted higher.

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>" || echo "Nothing to commit for questions"

echo ""
echo "=============================================="
echo "ALL PHASES COMPLETE — $(date)"
echo "=============================================="
$PYTHON "$RUNNER" tools/overnight/explainer-manifest.json --status
$PYTHON "$RUNNER" tools/overnight/questions-manifest.json --status
